export interface CardI {
    post_id: string,
    is_post_owner: boolean,
    owner: PostOwnerI,
    username: string,
    profileImage: string | null,
    occupation: string | null,
    created_at: string,
    text: string,
    post_liked: boolean,
    total_likes: number,
    total_comments: number,
    navigate_to_post?: () => void,
    navigate_to_profile?: () => void,
    query_update_post: (text: string, post_id?: string) => Promise<any>,
    query_like_post: (post_liked: boolean) => void,
    query_delete_post: () => void,
    query_report_post: () => void,
    query_hide_post: () => void,
    query_create_comment: (text: string) => Promise<any>,
    navigatingTo: string,
    toggle_create_comment_active: () => void,
    create_comment_active: boolean,
};

interface PostOwnerI {
    uid: string,
    username: string,
    profile_image: string | null,
    occupation: string | null,
}